### PR TITLE
Created view controller class Details

### PR DESCRIPTION
**Pull request by felipebweber**
Created view controller class Details and renamed ViewController class to MapViewController.

### CODE REVIEW

**Comment by henrique-morbin-ifood** [comment]
@felipebweber What is the purpose of your PR?

**Comment by henrique-morbin-ifood** [comment]
You could send small and valuable increments instead of empty view controllers.

**Comment by felipebweber** [comment]
The idea was to do this PR and continue the development. But I did a PR wrong without the functionality.
It was my mistake.
How to cancel a PR? So that the next PR with an implementation is done.
I have some features in the test code but I didn't put it in the main code because I want to do a PR later.
Sorry, I'm new to PR and collaborating with code.
My undergraduate and master's degree I did a good part of the implementation and then did the commit. I know I'm not sorry.
I am here to help and learn from the teachings and opinions of the most experienced. They are very welcome and I listen and improve.
My greatest intention is to help and thus have a closer contact than would be a development in a company.

**Comment by felipebweber** [comment]
How to cancel the PR? I want to submit another one with some implementations.

**Comment by lucasmontano** [comment]
I'm closing the PR for you :)

**Pull request closed without merging**
